name: 'coverage'
on:
  pull_request:
    branches:
      - '*'
jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Run tests with coverage
        run: poetry run coverage run -m pytest
      - name: Generate xml coverage file
        run: poetry run coverage xml
      - name: Get coverage
        uses: orgoro/coverage@3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}