name: Lint – Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout model-training repo
        uses: actions/checkout@v3

      - name: Checkout lib-ml repo
        uses: actions/checkout@v3
        with:
          repository: remla25-team20/lib-ml
          path: lib-ml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint
          pip install -e ./lib-ml

      - name: Run pylint
        run: pylint src/
