name: Release models

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
    train-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'
            
            - name: Install Poetry
              run: python -m pip install --upgrade pip |
                   pip install poetry
            
            - name: Install dependencies
              run: poetry install
            
            - name: Download data from gdrive
              run: poetry run python src/data/data_download.py

            - name: Preprocess data using lib-ml
              run: poetry run python src/data/preprocess.py

            - name: Train model
              run: poetry run python src/data/modeling/train.py

            - name: Release model and preprocessor
              id: release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  models/*
              env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}